### ISSUE TITLE
Nuspec update

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.ServiceCollection#4]
# Description
Update the nuspec file to address a few issues.

# Tasks
- [x] Update readme file
- [x] Fix issue with SourceLink
- [x] Make CI build deterministic
